#pragma once

// p2ce ver: revolution latest

typedef void* (*_CreateInterface)(const char*, int*);

#define VENGINESERVER_VERSION "VEngineServer023"
#define VENGINE_CLIENT_INTERFACE_VERSION "VEngineClient015"

class IVEngineClient {
public:
	virtual void vfunc0() = 0;
	virtual void vfunc1() = 0;
	virtual void vfunc2() = 0;
	virtual void vfunc3() = 0;
	virtual void vfunc4() = 0;
	virtual void vfunc5() = 0;
	virtual void vfunc6() = 0;
	virtual void vfunc7() = 0;
	virtual void vfunc8() = 0;
	virtual void vfunc9() = 0;
	virtual void vfunc10() = 0;
	virtual void vfunc11() = 0;
	virtual void vfunc12() = 0;
	virtual void vfunc13() = 0;
	virtual void vfunc14() = 0;
	virtual void vfunc15() = 0;
	virtual void vfunc16() = 0;
	virtual void vfunc17() = 0;
	virtual bool	IsPaused(void) = 0;
	virtual void vfunc19() = 0;
	virtual bool	IsLevelMainMenuBackground(void) = 0;
	virtual void vfunc21() = 0;
	virtual void vfunc22() = 0;
	virtual void vfunc23() = 0;
	virtual void vfunc24() = 0;
	virtual void vfunc25() = 0;
	virtual void vfunc26() = 0;
	virtual void vfunc27() = 0;
	virtual void vfunc28() = 0;
	virtual void vfunc29() = 0;
	virtual void vfunc30() = 0;
	virtual void vfunc31() = 0;
	virtual void vfunc32() = 0;
	virtual void vfunc33() = 0;
	virtual void vfunc34() = 0;
	virtual void vfunc35() = 0;
	virtual void vfunc36() = 0;
	virtual void vfunc37() = 0;
	virtual void vfunc38() = 0;
	virtual void vfunc39() = 0;
	virtual void vfunc40() = 0;
	virtual void vfunc41() = 0;
	virtual void vfunc42() = 0;
	virtual void vfunc43() = 0;
	virtual void vfunc44() = 0;
	virtual void vfunc45() = 0;
	virtual void vfunc46() = 0;
	virtual void vfunc47() = 0;
	virtual void vfunc48() = 0;
	virtual void vfunc49() = 0;
	virtual void vfunc50() = 0;
	virtual void vfunc51() = 0;
	virtual void vfunc52() = 0;
	virtual void vfunc53() = 0;
	virtual void vfunc54() = 0;
	virtual void vfunc55() = 0;
	virtual void vfunc56() = 0;
	virtual void vfunc57() = 0;
	virtual void vfunc58() = 0;
	virtual void vfunc59() = 0;
	virtual void vfunc60() = 0;
	virtual bool	IsInGame() = 0;
	virtual bool	IsConnected() = 0;
    virtual void vfunc63() = 0;
	virtual bool	IsDrawingLoadingImage() = 0;
	virtual void vfunc65() = 0;
	virtual void vfunc66() = 0;
	virtual void vfunc67() = 0;
	virtual void vfunc68() = 0;
	virtual void vfunc69() = 0;
	virtual void vfunc70() = 0;
	virtual void vfunc71() = 0;
	virtual void vfunc72() = 0;
	virtual void vfunc73() = 0;
	virtual void vfunc74() = 0;
	virtual void vfunc75() = 0;
	virtual void vfunc76() = 0;
	virtual void vfunc77() = 0;
	virtual void vfunc78() = 0;
	virtual void vfunc79() = 0;
	virtual void vfunc80() = 0;
	virtual void vfunc81() = 0;
	virtual void vfunc82() = 0;
    virtual char*   GetLevelName() = 0;
    virtual char*   GetLevelNameShort() = 0;
	virtual void vfunc85() = 0;
	virtual void vfunc86() = 0;
	virtual void vfunc87() = 0;
	virtual void vfunc88() = 0;
	virtual void vfunc89() = 0;
	virtual void vfunc90() = 0;
	virtual void vfunc91() = 0;
	virtual void vfunc92() = 0;
	virtual void vfunc93() = 0;
	virtual void vfunc94() = 0;
	virtual void vfunc95() = 0;
	virtual void vfunc96() = 0;
	virtual void vfunc97() = 0;
	virtual void vfunc98() = 0;
	virtual void vfunc99() = 0;
	virtual void vfunc100() = 0;
	virtual void vfunc101() = 0;
	virtual void vfunc102() = 0;
	virtual void vfunc103() = 0;
	virtual bool	IsPlayingDemo() = 0;
	virtual bool	IsRecordingDemo() = 0;
	virtual bool	IsPlayingTimeDemo() = 0;
	virtual int		GetDemoRecordingTick() = 0;
	virtual int		GetDemoPlaybackTick() = 0;
	virtual int		GetDemoPlaybackStartTick() = 0;
	virtual float	GetDemoPlaybackTimeScale() = 0;
	virtual int		GetDemoPlaybackTotalTicks() = 0;
	virtual void vfunc112() = 0;
	virtual void vfunc113() = 0;
	virtual void vfunc114() = 0;
	virtual void vfunc115() = 0;
	virtual void vfunc116() = 0;
	virtual void vfunc117() = 0;
	virtual void vfunc118() = 0;
	virtual void vfunc119() = 0;
	virtual void vfunc120() = 0;
	virtual void vfunc121() = 0;
	virtual void vfunc122() = 0;
	virtual void vfunc123() = 0;
	virtual void vfunc124() = 0;
	virtual void vfunc125() = 0;
	virtual void vfunc126() = 0;
	virtual void vfunc127() = 0;
	virtual void vfunc128() = 0;
	virtual void	ClientCmd_Unrestricted(const char* szCmdString, bool fromConsoleOrKeybind = false) = 0;
    virtual void vfunc130() = 0;
    virtual void vfunc131() = 0;
    virtual void vfunc132() = 0;
    virtual void vfunc133() = 0;
    virtual void vfunc134() = 0;
    virtual void vfunc135() = 0;
    virtual void vfunc136() = 0;
    virtual void vfunc137() = 0;
    virtual void vfunc138() = 0;
    virtual void vfunc139() = 0;
    virtual void vfunc140() = 0;
    virtual void vfunc141() = 0;
    virtual void vfunc142() = 0;
    virtual void vfunc143() = 0;
    virtual void vfunc144() = 0;
    virtual void vfunc145() = 0;
    virtual void vfunc146() = 0;
    virtual void vfunc147() = 0;
    virtual void vfunc148() = 0;
    virtual void vfunc149() = 0;
    virtual void vfunc150() = 0;
    virtual void vfunc151() = 0;
    virtual void vfunc152() = 0;
    virtual void vfunc153() = 0;
    virtual void vfunc154() = 0;
    virtual void vfunc155() = 0;
    virtual void vfunc156() = 0;
    virtual void vfunc157() = 0;
    virtual void vfunc158() = 0;
    virtual void vfunc159() = 0;
    virtual void vfunc160() = 0;
    virtual void vfunc161() = 0;
    virtual void vfunc162() = 0;
    virtual void vfunc163() = 0;
    virtual void vfunc164() = 0;
    virtual void vfunc165() = 0;
    virtual void vfunc166() = 0;
    virtual void vfunc167() = 0;
    virtual void vfunc168() = 0;
    virtual void vfunc169() = 0;
    virtual void vfunc170() = 0;
    virtual void vfunc171() = 0;
    virtual void vfunc172() = 0;
    virtual void vfunc173() = 0;
    virtual void vfunc174() = 0;
    virtual void vfunc175() = 0;
    virtual void vfunc176() = 0;
    virtual void vfunc177() = 0;
    virtual void vfunc178() = 0;
    virtual void vfunc179() = 0;
    virtual void vfunc180() = 0;
    virtual void vfunc181() = 0;
    virtual void vfunc182() = 0;
    virtual void vfunc183() = 0;
    virtual char* GetModDirectory(void) = 0;
};

extern IVEngineClient* engine;

#define FCVAR_CHEAT (1<<14)

class ConVar {
public:
    virtual void vfunc0() = 0;
    virtual void vfunc1() = 0;
    virtual void vfunc2() = 0;
    virtual void	AddFlags(int flags) = 0;
    virtual void	RemoveFlags(int flags) = 0;
};

class ICvar {
public:
    virtual void vfunc0() = 0;
    virtual void vfunc1() = 0;
    virtual void vfunc2() = 0;
    virtual void vfunc3() = 0;
    virtual void vfunc4() = 0;
    virtual void vfunc5() = 0;
    virtual void vfunc6() = 0;
    virtual void vfunc7() = 0;
    virtual void vfunc8() = 0;
    virtual void vfunc9() = 0;
    virtual void vfunc10() = 0;
    virtual void vfunc11() = 0;
    virtual void vfunc12() = 0;
    virtual void vfunc13() = 0;
    virtual void vfunc14() = 0;
    virtual void vfunc15() = 0;
    virtual void vfunc16() = 0;
    virtual void vfunc17() = 0;
    virtual void vfunc18() = 0;
    virtual ConVar* FindVar(const char* var_name) = 0;
};

extern ICvar* g_pCVar;
